eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8765
spring:
  application:
    name: api-gateway
    
  cloud:
    gateway:
      httpclient:
        response-timeout: 15000
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allow-credentials: true
            allowed-methods: 
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS